### ISSUE TITLE
Asset selection doesn't work. 2 bugs

### ISSUE THREAD

**Issue by o-alexandrov** [expo/UpdatesAPIDemo#14]
### Steps to reproduce

1. Clone this repo
2. Install deps `$ yarn` (I have yarn `v1` just fyi)
3. `$ npx expo export --dump-assetmap`
4. What's described in the [ASSETSELECTION.md](https://github.com/expo/UpdatesAPIDemo/blob/09372d4f0a1b8705f16a907ce6762f99682d5d7e/ASSETSELECTION.md) doesn't happen
    - the following part of the example isn't printed in the console:
    ```sh
    Exporting 1 asset:
    app/includedImages/white_blue.jpg (585 B)
    ```
    - in other words `white_blue.jpg` isn't selected

<details>
  <summary>Click to expand what's printed in my CLI</summary>
  
```sh
$ npx expo export --dump-assetmap
(node:44634) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting Metro Bundler
iOS Bundled 6040ms (node_modules/expo/AppEntry.js)
Web Bundled 12177ms (node_modules/expo/AppEntry.js)
Android Bundled 13618ms (node_modules/expo/AppEntry.js)
Android node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (992/992)
Processing asset bundle patterns:
- ../UpdatesAPIDemo/app/includedImages/*
Creating asset map

Exporting 1 bundle for ios:
_expo/static/js/ios/AppEntry-017d2e3433a069c0fb5c684cb010de3f.hbc (2.74 MB)

Exporting 1 bundle for android:
_expo/static/js/android/AppEntry-170fbea07b0951f50dc2be1d4968b90f.hbc (2.75 MB)

Exporting 1 bundle for web:
_expo/static/js/web/AppEntry-060700700e5ca19bb41d608bda85061c.js (1.54 MB)

Exporting 48 files:
assetmap.json (11.6 kB)
assets/assets/icons/back.eb51d8befd94e5d6aed211317f333ee0.png (411 B)
assets/assets/icons/back.eb51d8befd94e5d6aed211317f333ee0@2x.png (636 B)
assets/assets/icons/back.eb51d8befd94e5d6aed211317f333ee0@3x.png (782 B)
assets/assets/icons/bell.17f788d1a4168c77ad884a2efde7de3a.png (720 B)
assets/assets/icons/bell.17f788d1a4168c77ad884a2efde7de3a@2x.png (1.57 kB)
assets/assets/icons/bell.17f788d1a4168c77ad884a2efde7de3a@3x.png (2.28 kB)
assets/assets/icons/caretLeft.691bacbc6cf427242ebffc34af099e29.png (393 B)
assets/assets/icons/caretLeft.691bacbc6cf427242ebffc34af099e29@2x.png (614 B)
assets/assets/icons/caretLeft.691bacbc6cf427242ebffc34af099e29@3x.png (704 B)
assets/assets/icons/caretRight.4e92523c1ef4ee6507d7f7c0c4b852a4.png (367 B)
assets/assets/icons/caretRight.4e92523c1ef4ee6507d7f7c0c4b852a4@2x.png (602 B)
assets/assets/icons/caretRight.4e92523c1ef4ee6507d7f7c0c4b852a4@3x.png (723 B)
assets/assets/icons/check.64349be9c1616413ea8c9f1063f62824.png (404 B)
assets/assets/icons/check.64349be9c1616413ea8c9f1063f62824@2x.png (623 B)
assets/assets/icons/check.64349be9c1616413ea8c9f1063f62824@3x.png (776 B)
assets/assets/icons/debug.cb7f1047a9ce92bb860d98ed493dfb64.png (411 B)
assets/assets/icons/debug.cb7f1047a9ce92bb860d98ed493dfb64@2x.png (678 B)
assets/assets/icons/debug.cb7f1047a9ce92bb860d98ed493dfb64@3x.png (887 B)
assets/assets/icons/hidden.aa2f04bf8a4c3cc1e946d28eadb753ce.png (1.06 kB)
assets/assets/icons/hidden.aa2f04bf8a4c3cc1e946d28eadb753ce@2x.png (2.25 kB)
assets/assets/icons/hidden.aa2f04bf8a4c3cc1e946d28eadb753ce@3x.png (3.38 kB)
assets/assets/icons/lock.8140cacfefce289c039b6ecb6ba1330c.png (618 B)
assets/assets/icons/lock.8140cacfefce289c039b6ecb6ba1330c@2x.png (1.15 kB)
assets/assets/icons/lock.8140cacfefce289c039b6ecb6ba1330c@3x.png (1.69 kB)
assets/assets/icons/menu.b7b65e80565a3c8e6bba979df3eaf922.png (227 B)
assets/assets/icons/menu.b7b65e80565a3c8e6bba979df3eaf922@2x.png (342 B)
assets/assets/icons/menu.b7b65e80565a3c8e6bba979df3eaf922@3x.png (484 B)
assets/assets/icons/more.399e7f2bf5eaec3c43c10bead95d216e.png (243 B)
assets/assets/icons/more.399e7f2bf5eaec3c43c10bead95d216e@2x.png (394 B)
assets/assets/icons/more.399e7f2bf5eaec3c43c10bead95d216e@3x.png (569 B)
assets/assets/icons/sdk.a7f0f56c6ac02fc4ea9a2166c4141f93.png (14.5 kB)
assets/assets/icons/settings.8b8288505a077374f0847b3c9727beec.png (1.25 kB)
assets/assets/icons/settings.8b8288505a077374f0847b3c9727beec@2x.png (2.89 kB)
assets/assets/icons/settings.8b8288505a077374f0847b3c9727beec@3x.png (4.47 kB)
assets/assets/icons/view.2dddc7c09acf9aebc7d7aad9e280f91f.png (796 B)
assets/assets/icons/view.2dddc7c09acf9aebc7d7aad9e280f91f@2x.png (1.89 kB)
assets/assets/icons/view.2dddc7c09acf9aebc7d7aad9e280f91f@3x.png (2.81 kB)
assets/assets/icons/x.6fc97ee4a52d47782870ca094a34dc27.png (472 B)
assets/assets/icons/x.6fc97ee4a52d47782870ca094a34dc27@2x.png (814 B)
assets/assets/icons/x.6fc97ee4a52d47782870ca094a34dc27@3x.png (1.01 kB)
assets/node_modules/@expo-google-fonts/space-grotesk/SpaceGrotesk_300Light.7e767880def9016b433bab4d6493d899.ttf (86.6 kB)
assets/node_modules/@expo-google-fonts/space-grotesk/SpaceGrotesk_400Regular.155c2e8af05b78017012be8ff2962731.ttf (86.5 kB)
assets/node_modules/@expo-google-fonts/space-grotesk/SpaceGrotesk_500Medium.d52e2a5ca7f9d70f174ac0a7095dbccf.ttf (86.5 kB)
assets/node_modules/@expo-google-fonts/space-grotesk/SpaceGrotesk_600SemiBold.85caebdc62414beb10457fdc6ca2d4c2.ttf (86.5 kB)
assets/node_modules/@expo-google-fonts/space-grotesk/SpaceGrotesk_700Bold.b6d08fb2f89a7b71dd0ca70ce941c922.ttf (86.4 kB)
index.html (1.18 kB)
metadata.json (250 B)

App exported to: dist
```

</details>
    
### Steps to reproduce

1. Clone this repo
2. Install deps `$ yarn`
3. Run `$ yarn verify-assets:ios`
4. Observe CLI error:
  `Error: ENOENT: no such file or directory, open '../UpdatesAPIDemo/ios/build/Build/Products/Release-iphonesimulator/EXUpdates/EXUpdates.bundle/app.manifest'`
  
<details>
  <summary>Click to expand what's printed in my CLI</summary>
  
```sh
$ yarn verify-assets:ios
yarn run v1.22.21
$ npx expo export --dump-assetmap -p ios; npx expo-updates assets:verify --build-manifest-path ios/build/Build/Products/Release-iphonesimulator/EXUpdates/EXUpdates.bundle/app.manifest --exported-manifest-path dist/metadata.json --asset-map-path dist/assetmap.json --platform ios
(node:44329) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting Metro Bundler
iOS Bundled 10348ms (node_modules/expo/AppEntry.js)
iOS node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (993/993)
Processing asset bundle patterns:
- ../UpdatesAPIDemo/app/includedImages/*
Creating asset map

Exporting 1 bundle for ios:
_expo/static/js/ios/AppEntry-017d2e3433a069c0fb5c684cb010de3f.hbc (2.74 MB)

Exporting 2 files:
assetmap.json (11.6 kB)
metadata.json (145 B)

App exported to: dist
Error: ENOENT: no such file or directory, open '../UpdatesAPIDemo/ios/build/Build/Products/Release-iphonesimulator/EXUpdates/EXUpdates.bundle/app.manifest'
error Command failed with exit code 1.
```

</details>

**Comment by o-alexandrov** [comment]
cc'ing @douglowder @wschurman since you worked on https://github.com/expo/UpdatesAPIDemo/pull/13

**Comment by douglowder** [comment]
Seems like you might not have executed `yarn select-images` before building, per the tutorial instructions.

**Comment by o-alexandrov** [comment]
@douglowder thank you for the reply.

> Seems like you might not have executed yarn select-images before building, per the tutorial instructions.

There's no code related to `app/includedImages` in `scripts/select-images.js`, but I ran as you suggested:

1. `yarn select-images`
2. then again: `npx expo export --dump-assetmap`

Nothing changed, same CLI output without `white_blue.jpg`

---

Whereas regarding, `yarn ios --configuration Release`, I tried it, and had another bug (it expected to have iOS 17.2 to be installed, whereas I have iOS 17.0 installed). I'll update iOS in Xcode and ping back about it.

```sh
$ yarn ios --configuration Release
yarn run v1.22.21
$ npx expo run:ios --configuration Release
(node:48620) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Created native directory
› Using current versions instead of recommended react-native@0.73.4.
✔ Updated package.json | no changes
✔ Finished prebuild
✔ Installed CocoaPods
› Planning build

› 0 error(s), and 0 warning(s)

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 70.
To view more error logs, try building the app with Xcode directly, by opening ../UpdatesAPIDemo/ios/UpdatesAPIDemo.xcworkspace.

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ../UpdatesAPIDemo/ios/UpdatesAPIDemo.xcworkspace -configuration Release -scheme UpdatesAPIDemo -destination id=972F86FC-4CB0-4A03-AAB8-5D0049FC1C8E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES



2024-02-13 00:37:37.088 xcodebuild[49304:24241846] Writing error result bundle to /var/folders/9v/3nxlbmh955567py7f0w9ptj00000gn/T/ResultBundle_2024-13-02_00-37-0037.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                { id:972F86FC-4CB0-4A03-AAB8-5D0049FC1C8E }

        Ineligible destinations for the "UpdatesAPIDemo" scheme:
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 17.2 is not installed. To use with Xcode, first download and install the platform }
Build logs written to ../UpdatesAPIDemo/.expo/xcodebuild.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by douglowder** [comment]
If you follow the steps from `ASSETSELECTION.md`, in order, the demo will work. Here they are all together for iOS.

```bash
# Install dependencies
yarn
# Modify source code to add embedded images
yarn select-images
# EAS configuration
eas init
eas update:configure
# Run prebuild
npx expo prebuild --clean
# Build the app locally
npx expo run:ios --configuration Release
# Modify source code to add all JPG images in the app folder to assets.ts
yarn select-images app/*/*.jpg
# Execute an EAS update
yarn update -m "Add some images"
# Verify assets (it will fail due to one image not included in the update
yarn verify-assets:ios
```

### Embedded assets

The build will include two image files, both in the `app/embeddedImages` folder. These assets will be available to the initial build, and to all subsequent updates. When running the initial build, you will see these two images in the "Image Assets" card on the home screen.

![assets-01-embedded-images](./media/assets-01-embedded-images.jpg)

### Assets included in updates

This app has a folder `app/includedImages`. The Expo config for the app contains an `extra.updates.assetPatternsToBeBundled` setting so that only images in this folder are included in updates.

#### Add images and create an update

You can now use the `select-images` script to add images to the asset imports in `app/components/ExpoAssets/assets.ts`. All the images you add will be resolved by the Metro bundler, but only assets in `app/includedImages` will be packaged into updates.

While the app is running in the simulator/emulator, execute

```bash
# Add all JPG images in the app folder to assets.ts
yarn select-images app/*/*.jpg
# Execute an EAS update
yarn update -m "Add some images"
```

In the app, click "Show monitor options", then check the checkbox labeled "Check every 10 seconds". After a few seconds, the monitor will show at the bottom of the screen, alerting the user that an update is available, and some details about the update, including the message from `app.json`.

Click "Download" to fetch the update, and "Launch" to restart the app with the new update bundle.

The "Image Assets" card on the home screen now shows the original images from the `app/embeddedImages` folder. A new image is now included from the `app/includedImages` folder -- this folder is included in the asset selection patterns in `app.json`. The app attempts to show another new image in `app/excludedImages`. This image is resolved by the Metro bundler, but not included in the update or in the original app build, so the image does not show on the screen.

![assets-02-updated-images](./media/assets-02-updated-images.jpg)

#### Checking locally to ensure that all needed assets are included in an update

Since it is desirable to check for missing images before an update is published, a command has been added to the `expo-updates` CLI to allow users to make this check:

```
$ npx expo-updates assets:verify --help

Description
Verify that all static files in an exported bundle are in either the export or an embedded bundle

Usage
  $ npx expo-updates assets:verify <dir>

  Options
  <dir>                                  Directory of the Expo project. Default: Current working directory
  -a, --asset-map-path <path>            Path to the `assetmap.json` in an export produced by the command `npx expo export --dump-assetmap`
  -e, --exported-manifest-path <path>    Path to the `metadata.json` in an export produced by the command `npx expo export --dump-assetmap`
  -b, --build-manifest-path <path>       Path to the `app.manifest` file created by expo-updates in an Expo application build (either ios or android)
  -p, --platform <platform>              Options: ["android","ios"]
  -h, --help                             Usage info

```

> Eventually, we plan to use this command as part of the `eas update` flow so that EAS will automatically verify that updates have all assets that they need.

To ensure that the command produces valid results, you will need access to the `app.manifest` file generated in Android and iOS builds where `expo-updates` is enabled. This file lists all assets that were resolved by Metro and included in the app during the build.

This check also requires files from the update bundle, specifically the `metadata.json` and `assetmap.json` in the update bundle. When making this check locally during application development, you can at any time generate the same bundle used by EAS Update (or a custom update server) by executing `npx expo export --dump-assetmap`.

For convenience, this demo app includes scripts in `package.json` that execute the above command to generate the update bundle, then perform the check against a local build. The scripts assume that you have built the app locally with `yarn ios --configuration Release` or `yarn android --variant release`.

For example, if we have followed the instructions above to select all images in the `app/` directory, and published an update, there is a single image missing from the update. If we run the demo script, this missing image is detected by the `expo-updates` CLI tool, and the tool returns exit code 1, indicating the missing image error:

```
$ yarn verify-assets:ios
